name: Tests Terrafrorm code
on: 
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy to"
                required: true
                default: dev
                type: choice
                options:
                    - dev
                    - staging
                    - prod


jobs:
    initialization:
        runs-on: ubuntu-latest
        if: ${{ inputs.environment == 'dev' }}
        steps:
            - name: "Setup terraform"
              uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1
            
            - name: "Checkout code"
              uses: actions/checkout@v3
              
            - name: "Terraform init"
              run: terraform init 
            
